[package]
name = "tenant-resolver-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "SDK for tenant_resolver plugin example: API trait, models, and errors"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }
modkit-security = { path = "../../../../libs/modkit-security" }
modkit-odata = { path = "../../../../libs/modkit-odata" }
schemars = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# GTS
gts = { workspace = true }
gts-macros = { workspace = true }
uuid = { workspace = true }


