[package]
name = "cf-simple-user-settings-sdk"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "SDK for simple-user-settings module: API trait, types, and error definitions"
repository.workspace = true
readme = "README.md"
keywords = ["cyberfabric", "cyberfabric-system"]
categories = ["web-programming"]

[lib]
name = "simple_user_settings_sdk"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
time = { workspace = true }

modkit = { workspace = true }
modkit-macros = { workspace = true }
modkit-security = { workspace = true }
