[package]
name = "tenant-resolver-gw"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Tenant resolver gateway module (plugin example)"

[lib]
name = "tenant_resolver_example_gw"

[lints]
workspace = true

[dependencies]
# SDKs
tenant-resolver-example-sdk = { package = "tenant-resolver-sdk", path = "../tenant-resolver-sdk" }
types-registry-sdk = { workspace = true }

# ModKit
modkit = { workspace = true }
types = { path = "../../../../modules/system/types" }
modkit-security = { workspace = true }
modkit-odata = { workspace = true, features = ["with-utoipa"] }
modkit-macros = { workspace = true }

# HTTP/REST
axum = { workspace = true }
http = { workspace = true }
utoipa = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Async & misc
async-trait = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
inventory = { workspace = true }
arc-swap = { workspace = true }
tokio = { workspace = true, features = ["sync"] }

thiserror = { workspace = true }
