[package]
name = "de0202_dtos_not_referenced_outside_api"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "20ce69b9a63bcd2756cd906fe0964d1e901e042a" }
dylint_linting = "5.0.0"
lint_utils = { path = "../../lint_utils" }

[dev-dependencies]
dylint_testing = "5.0.0"

[package.metadata.rust-analyzer]
rustc_private = true

[[example]]
name = "import_dto_in_contract"
path = "ui/import_dto_in_contract.rs"

[[example]]
name = "import_dto_in_domain"
path = "ui/import_dto_in_domain.rs"

[[example]]
name = "import_dto_in_api"
path = "ui/import_dto_in_api.rs"
