[package]
name = "analytics"
version = "0.1.0"
edition = "2021"

[dependencies]
analytics-sdk = { path = "../analytics-sdk" }
modkit = { path = "../../../libs/modkit" }
modkit-db = { path = "../../../libs/modkit-db" }
modkit-db-macros = { path = "../../../libs/modkit-db-macros" }
modkit-auth = { path = "../../../libs/modkit-auth" }
modkit-security = { path = "../../../libs/modkit-security" }
modkit-odata = { path = "../../../libs/modkit-odata" }
async-trait = "0.1"
axum = "0.8"
anyhow = "1.0"
tracing = "0.1"
inventory = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
gts = { workspace = true }
tower = "0.5"
tokio = { version = "1.47", features = ["full"] }
urlencoding = "2.1"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = "0.4"
utoipa = { workspace = true }
