[package]
name = "de0701_no_unwrap"
version = "0.1.0"
authors = ["Hypernetix"]
description = "Detects usage of .unwrap() method calls (DE0701)"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[[example]]
name = "bad_unwrap"
path = "ui/bad_unwrap.rs"

[[example]]
name = "good_error_handling_0701"
path = "ui/good_error_handling_0701.rs"

[dependencies]
clippy_utils.workspace = true
dylint_linting.workspace = true
lint_utils.workspace = true

[dev-dependencies]
dylint_testing.workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
