[package]
name = "tenant-resolver-sdk"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "SDK for tenant-resolver plugin example: API trait, models, and errors"

[lib]
name = "tenant_resolver_example_sdk"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }
modkit = { workspace = true }
modkit-security = { workspace = true }
modkit-odata = { workspace = true }
schemars = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# GTS
gts = { workspace = true }
gts-macros = { workspace = true }
uuid = { workspace = true }
