[package]
name = "simple-user-settings"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
simple-user-settings-sdk = { path = "../simple-user-settings-sdk" }

anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
inventory = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }
axum = { workspace = true, features = ["macros"] }
uuid = { workspace = true }
arc-swap = { workspace = true }
sea-orm = { workspace = true, features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros", "with-time", "with-uuid"] }
sea-orm-migration = { workspace = true }
thiserror = { workspace = true }

modkit = { path = "../../../libs/modkit" }
modkit-auth = { path = "../../../libs/modkit-auth" }
modkit-db = { path = "../../../libs/modkit-db", features = ["insecure-escape"] }
modkit-db-macros = { path = "../../../libs/modkit-db-macros" }
modkit-errors = { path = "../../../libs/modkit-errors" }
modkit-errors-macro = { path = "../../../libs/modkit-errors-macro" }
modkit-security = { path = "../../../libs/modkit-security" }
