[package]
name = "nodes_registry"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
inventory = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }
axum = { workspace = true, features = ["macros"] }
tower-http = { workspace = true, features = ["timeout"] }
futures = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true }
arc-swap = { workspace = true }
thiserror = { workspace = true }

modkit = { path = "../../libs/modkit" }
modkit-node-info = { path = "../../libs/modkit-node-info" }

[dev-dependencies]
tower = { workspace = true, features = ["util"] }
api_ingress = { path = "../../modules/api_ingress" }
