[package]
name = "tenant_resolver-gw"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Tenant resolver gateway module (plugin example)"

[lints]
workspace = true

[dependencies]
# SDKs
tenant-resolver-sdk = { path = "../tenant_resolver-sdk" }
types-registry-sdk = { path = "../../../../modules/system/types-registry/types-registry-sdk" }

# ModKit
modkit = { workspace = true }
modkit-security = { workspace = true }
modkit-odata = { workspace = true, features = ["with-utoipa"] }
modkit-macros = { workspace = true }

# HTTP/REST
axum = { workspace = true }
http = { workspace = true }
utoipa = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Async & misc
async-trait = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
inventory = { workspace = true }
arc-swap = { workspace = true }
tokio = { workspace = true, features = ["sync"] }

thiserror = { workspace = true }
