name: ADR Lint

on:
  pull_request:
    paths:
      - 'docs/adrs/**'
      - 'modules/**/docs/adrs/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint ADRs
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.pull_request.labels.*.name, 'release-plz')
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Lint ADR markdown files
        uses: DavidAnson/markdownlint-cli2-action@05f32210e84442804257b2a6f20b273450ec8265 # v19.1.0
        with:
          config: docs/adrs/.markdownlint.yml
          globs: |
            docs/adrs/**/*.md
            modules/**/docs/adrs/**/*.md
