[package]
name = "module_orchestrator-contracts"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Domain contracts and client interfaces for module orchestrator"

[dependencies]
async-trait = { workspace = true }
anyhow = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }





